# Generated by Django 6.1 on 2026-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Include country code, e.g. +919876543210', max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Include country code, no + or spaces, e.g. 919876543210', max_length=20)),
                ('whatsapp_message', models.CharField(default="Hi, I'd like to enquire about a photoshoot.", help_text='Pre-filled message when someone clicks the WhatsApp button', max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
