# Generated by Django 6.1 on 2026-08-19 06:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Illuminating Life's Beautiful Moments", max_length=200)),
                ('subtitle', models.TextField(default='The best for all your photography needs, immortalizing your moments in immersive art.')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('primary_button_text', models.CharField(default='Book Now', max_length=50)),
                ('primary_button_link', models.CharField(default='#contact', max_length=200)),
                ('secondary_button_text', models.CharField(default='View Portfolio', max_length=50)),
                ('secondary_button_link', models.CharField(default='#portfolio', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='LUMORA STUDIO', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.CharField(default="Hi, I'd like to enquire about a photoshoot.", max_length=255),
        ),
    ]
