# Generated by Django 6.1 on 2026-08-19 07:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_herosection_sitesettings_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtiesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='What We Do', max_length=100)),
                ('heading', models.CharField(default='Our Specialties', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialtyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Weddings, Portraits, Newborns', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
