# Generated by Django 6.1 on 2026-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_specialtiessection_specialtyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='The number, e.g. 500')),
                ('suffix', models.CharField(blank=True, default='', help_text='e.g. +, %, or leave blank', max_length=10)),
                ('label', models.CharField(help_text='e.g. Sessions Captured', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
