# Generated by Django 6.1 on 2026-08-19 07:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_statitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='e.g. WEDDING, PORTRAIT', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedWorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Portfolio Highlights', max_length=100)),
                ('heading', models.CharField(default='Featured Work', max_length=200)),
                ('subtext', models.CharField(default="A closer look at the moments we've had the honor to capture.", max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
