# Generated by Django 6.1 on 2026-08-19 08:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_featuredshoot_featuredworksection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shoot', models.CharField(help_text='e.g. WEDDING, FAMILY SESSION', max_length=100)),
                ('quote', models.TextField()),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Testimonials', max_length=100)),
                ('heading', models.CharField(default='Client Stories', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
