# Generated by Django 6.1 on 2026-08-19 09:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_instagramimage_instagramsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Book a Session', max_length=100)),
                ('heading', models.CharField(default="Let's Make Something Worth Keeping", max_length=200)),
                ('subtext', models.TextField(default='We take a limited number of commissions each month so every story gets the attention it deserves. Tell us about yours.')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('footer_note', models.CharField(default='Replies within 48 hours · Studio in Bangalore · Travels worldwide', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
