# Generated by Django 6.1 on 2026-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_ctasection_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Questions', max_length=100)),
                ('heading', models.CharField(default='Good To Know', max_length=200)),
                ('subtext', models.TextField(default='Everything couples and families ask us before the first frame. Anything else, just write — we answer personally.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
