# Generated by Django 6.1 on 2026-08-19 09:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_faqitem_faqsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='How We Work', max_length=100)),
                ('heading', models.CharField(default='From Vision to Frame', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02, 03', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Meet the Studio', max_length=100)),
                ('name', models.CharField(default='Elena Voss', max_length=100)),
                ('role', models.CharField(default='Founder & Lead Photographer', max_length=150)),
                ('bio_paragraph_1', models.TextField(default="I started Lumora after photographing my sister's first morning as a mother — one frame, no direction, and everything already there. Twelve years later I still work the same way: quietly, in natural light, waiting for the room to forget I'm in it.")),
                ('bio_paragraph_2', models.TextField(default='Every session is built around your people and your pace, never a shot list.')),
                ('quote', models.TextField(default='A photograph should feel less like a pose and more like a memory you can hold.')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
