# Generated by Django 6.1 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_processsection_processstep_studiosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(default='An editorial photography studio shaped around natural light, quiet direction, and images that still feel true in twenty years.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
