# Generated by Django 6.1 on 2026-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_footersection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManifestoSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(default="Our Philosophy", max_length=100),
                ),
                (
                    "statement",
                    models.TextField(
                        default="We don't direct moments — we wait for them. Every frame we deliver is one you'd have wanted to remember, even if we hadn't been there to capture it."
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional, e.g. 'Elena Voss, Founder'",
                        max_length=150,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(default="By the Numbers", max_length=100),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=200)),
                (
                    "subtext",
                    models.CharField(
                        blank=True,
                        default="Numbers can't capture a wedding day, but they tell you we've done this before.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="herosection",
            name="trust_line",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Small credibility line under the buttons, e.g. '500+ sessions captured · Bangalore, worldwide'",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="instagramsection",
            name="subtext",
            field=models.CharField(
                blank=True,
                default="Behind-the-scenes and unposted favorites — updated weekly.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="specialtyitem",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short one-line description shown under the label, e.g. 'Timeless coverage from first look to last dance'",
                max_length=160,
            ),
        ),
    ]